name: Latest awesome code review workflow
on:
 schedule: # Run workflow automatically
   # This will make it run every hour
   - cron: '0 2 * * *' 
  # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
 workflow_dispatch: 
jobs:
 update-readme-with-blog:
   name: Update this repo's README with latest podcast episodes
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: gautamkrishnar/blog-post-workflow@master
       with:
          comment_tag_name: "AWESOMECODEREVIEW-LIST"
          commit_message: "Updated readme with the latest se-unlocked podcast episode"
          feed_list: "https://www.awesomecodereviews.com/rss.xml"
